config/routes.rb
Recruitment::Application.routes.draw do
  resources :applicants

  get "login5/login_page"
 post "login5/login_page"
post "login5/logout"

  get "login4/login_page"
  post "login4/login_page"
post "login4/logout"

  get "login3/login_page"
post "login3/login_page"
post "login3/logout"

  get "login2/login_page"
post "login2/login_page"
post "login2/logout"

  get "login1/login_page"
        post "login1/login_page"
        post "login1/logout"

 

  get "login/login_page"
  post "login/login_page"
post "login/logout"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :referrals

  resources :roles

  resources :rounds

  resources :sourcingpartners

  resources :technologies

  resources :interviewers

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  scope :todays_interview,where( 'scheduleofinterview between ? and ?', Date.today, Date.tomorrow)
  attr_accessible :email, :interviewers, :name, :role, :round, :scheduleofinterview, :sourcingpartner, :status, :technology, :cv
  has_attached_file :cv,
                    :url  => "/assets/products/:id/original/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/original/:basename.:extension"

  validates_attachment_content_type :cv,
      :content_type => [ 'application/pdf','application/msword'],
      :message => "only pdf and word files are allowed"
      validates :email, :uniqueness => true
    validates :email, :format => { :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/,
    :message => "Wrong Format" }
        validates_presence_of :email, :interviewers, :name, :role, :round, :scheduleofinterview, :sourcingpartner, :status, :technology, :cv

def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end

end

app/models/interviewer.rb
class Interviewer < ActiveRecord::Base
  attr_accessible :email, :name, :role
  validates :email, :uniqueness => true
    validates :email, :format => { :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/,
    :message => "Wrong Format" }
    validates_presence_of :email, :name, :role

def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end


end

app/models/login_info.rb
class LoginInfo < ActiveRecord::Base
  attr_accessible :password, :username
end

app/models/login_info1.rb
class LoginInfo1 < ActiveRecord::Base
  attr_accessible :password, :username
end

app/models/login_info2.rb
class LoginInfo2 < ActiveRecord::Base
  attr_accessible :password, :username
end

app/models/login_info3.rb
class LoginInfo3 < ActiveRecord::Base
  attr_accessible :password, :username
end

app/models/login_info4.rb
class LoginInfo4 < ActiveRecord::Base
  attr_accessible :password, :username
end

app/models/login_info5.rb
class LoginInfo5 < ActiveRecord::Base
  attr_accessible :password, :username
end

app/models/referral.rb
class Referral < ActiveRecord::Base
  attr_accessible :email, :name, :referredby, :role, :technology, :cv
  has_attached_file :cv,
                    :url  => "/assets/products/:id/original/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/original/:basename.:extension"

  validates_attachment_content_type :cv,
      :content_type => [ 'application/pdf','application/msword'],
      :message => "only pdf and word files are allowed"
      validates :email, :uniqueness => true
    validates :email, :format => { :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/,
    :message => "Wrong Format" }
        validates_presence_of :email, :name, :referredby, :role, :technology, :cv

def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end


end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :description, :name
  validates :name, :uniqueness => true
          validates_presence_of :name
          
def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end


end

app/models/round.rb
class Round < ActiveRecord::Base
  attr_accessible :description, :name
    validates :name, :uniqueness => true
          validates_presence_of :name

def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end


end

app/models/technology.rb
class Technology < ActiveRecord::Base
  attr_accessible :description, :name
    validates :name, :uniqueness => true
          validates_presence_of :name

def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end


end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.search(params[:name])

if !session[:logged_in]
  redirect_to :controller => 'login2', 
              :action => 'login_page' 
  return
end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @technologies }
    end
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
    @technology = Technology.find(params[:id])
if !session[:logged_in]
  redirect_to :controller => 'login2', 
              :action => 'login_page' 
  return
end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @technology }
    end
  end

  # GET /technologies/new
  # GET /technologies/new.json
  def new
    @technology = Technology.new

if !session[:logged_in]
  redirect_to :controller => 'login2', 
              :action => 'login_page' 
  return
end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @technology }
    end
  end

  # GET /technologies/1/edit
  def edit
    @technology = Technology.find(params[:id])
  if !session[:logged_in]
  redirect_to :controller => 'login2', 
              :action => 'login_page' 
  return
end
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(params[:technology])

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render json: @technology, status: :created, location: @technology }
      else
        format.html { render action: "new" }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /technologies/1
  # PUT /technologies/1.json
  def update
    @technology = Technology.find(params[:id])

    respond_to do |format|
      if @technology.update_attributes(params[:technology])
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology = Technology.find(params[:id])
    @technology.destroy

if !session[:logged_in]
  redirect_to :controller => 'login2', 
              :action => 'login_page' 
  return
end

    respond_to do |format|
      format.html { redirect_to technologies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/login1_helper.rb
module Login1Helper
end

app/helpers/login2_helper.rb
module Login2Helper
end

app/helpers/login3_helper.rb
module Login3Helper
end

app/helpers/login4_helper.rb
module Login4Helper
end

app/helpers/login5_helper.rb
module Login5Helper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/technologies/_form.html.erb
<%= form_for @technology, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                technologies_path, :class => 'btn' %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<%- model_class = Technology -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/technologies/index.html.erb
<%- model_class = Technology -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
   <form class="form-search">

    <%= text_field_tag :name, params[:name] %>

    <button type="submit" class="btn">Search</button>
    </form>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= link_to technology.id, technology_path(technology) %></td>
        <td><%= technology.name %></td>
        <td><%= technology.description %></td>
        <td><%=l technology.created_at %></td>
        <td>
                                  <%= link_to 'Show', technology %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_technology_path(technology), :class => 'btn btn-mini' %>
          <%= link_to t('.delete', :default => t("helpers.links.delete")),
                      technology_path(technology),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_technology_path,
            :class => 'btn btn-primary' %>

app/views/technologies/new.html.erb
<%- model_class = Technology -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/technologies/show.html.erb
<%- model_class = Technology -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @technology.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @technology.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              technologies_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_technology_path(@technology), :class => 'btn' %>
  <%= link_to t('.delete', :default => t("helpers.links.delete")),
              technology_path(@technology),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>